
CREATE TABLE CAD_PARAMETROS (
  CD_PARAMETROS INTEGER   NOT NULL ,
  DS_SV_PROXY VARCHAR(100)    ,
  NR_PT_PROXY INTEGER    ,
  US_PROXY VARCHAR(60)    ,
  PW_PROXY VARCHAR(20)    ,
  DIR_LOTES_GERADOS VARCHAR(100)    ,
  DOR_LOTES_AUTORIZADOS VARCHAR(100)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_PARAMETROS));

CREATE TABLE CAD_CERTIFICADO_DIGITAL (
  CD_CERTIFICADO INTEGER   NOT NULL ,
  NM_CERTIFICADO VARCHAR(60)    ,
  NR_CNPJ VARCHAR(15)    ,
  DT_VALIDADE DATE    ,
  DS_EMISSOR VARCHAR(100)    ,
  DS_LOCAL_ARQUIVO VARCHAR(100)    ,
  TP_ARQUIVO VARCHAR(10)    ,
  DS_LOCAL_BIBLIOTECAPKCS11 VARCHAR(100)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_CERTIFICADO));

CREATE TABLE CAD_SERVICOS_WEB (
  CD_SERVICO INTEGER   NOT NULL ,
  NM_SERVICO VARCHAR(60)    ,
  DS_VERSAO VARCHAR(10)    ,
  DS_URL VARCHAR(300)    ,
  IN_SVAN CHAR(1)    ,
  IN_SVRS CHAR(1)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_SERVICO));

CREATE TABLE CAD_USUARIO (
  CD_USUARIO INTEGER   NOT NULL ,
  NM_USUARIO VARCHAR(60)    ,
  NM_LOGIN VARCHAR(10)    ,
  PW_SENHA VARCHAR(8)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_USUARIO));

CREATE TABLE CAD_PAIS (
  CD_PAIS INTEGER   NOT NULL ,
  NM_PAIS VARCHAR(60)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_PAIS));

CREATE TABLE CAD_UF (
  CD_UF INTEGER   NOT NULL ,
  CD_PAIS INTEGER   NOT NULL ,
  SG_UF CHAR(2)    ,
  NM_UF VARCHAR(60)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_UF)  ,
  FOREIGN KEY(CD_PAIS)
    REFERENCES CAD_PAIS(CD_PAIS));

CREATE TABLE CAD_CIDADE (
  CD_CIDADE INTEGER   NOT NULL ,
  CD_UF INTEGER   NOT NULL ,
  NM_CIDADE VARCHAR(100)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_CIDADE)  ,
  FOREIGN KEY(CD_UF)
    REFERENCES CAD_UF(CD_UF));

CREATE TABLE CAD_ENDERECO (
  CD_ENDERECO INTEGER   NOT NULL ,
  CD_CIDADE INTEGER   NOT NULL ,
  DS_LOGRADOURO VARCHAR(120)    ,
  DS_NUMERO VARCHAR(40)    ,
  DS_COMPLEMENTO VARCHAR(40)    ,
  DS_BAIRRO VARCHAR(80)    ,
  NR_CEP VARCHAR(10)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_ENDERECO)  ,
  FOREIGN KEY(CD_CIDADE)
    REFERENCES CAD_CIDADE(CD_CIDADE));

CREATE TABLE CAD_REGIME_TRIBUTARIO (
  CD_REGIME INTEGER   NOT NULL ,
  DS_REGIME VARCHAR(60)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_REGIME));

CREATE TABLE CAD_OPERACAO (
  CD_OPERACAO INTEGER   NOT NULL ,
  NM_OPERACAO VARCHAR(60)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_OPERACAO));

CREATE TABLE CAD_MODALIDADE_TRANSPORTE (
  CD_MODALIDADE INTEGER   NOT NULL ,
  DS_MODALIDADE VARCHAR(60)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_MODALIDADE));

drop  domain lo cascade ;
create domain lo as oid;

CREATE TABLE CAD_EMITENTE (
  CD_EMITENTE INTEGER   NOT NULL ,
  CD_REGIME INTEGER   NOT NULL ,
  NM_RZ_SOCIAL VARCHAR(60)    ,
  NR_CNPJ_CPF VARCHAR(11)    ,
  NR_INCRI_EST VARCHAR(11)    ,
  NM_FANTASIA VARCHAR(60)    ,
  DS_CENAE_FISCAL VARCHAR(60)    ,
  NR_INCRI_MUNICIPAL VARCHAR(15)    ,
  IMG_LOGO lo    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_EMITENTE)  ,
  FOREIGN KEY(CD_REGIME)
    REFERENCES CAD_REGIME_TRIBUTARIO(CD_REGIME));
	
CREATE TABLE CAD_CLIENTE (
  CD_CLIENTE INTEGER   NOT NULL ,
  NM_RZ_SOCIAL INTEGER    ,
  NR_CNPJ_CPF VARCHAR(11)    ,
  NR_INSCRI_EST VARCHAR(15)    ,
  DS_ANTT VARCHAR(60)    ,
  DS_EMAIL VARCHAR(60)    ,
  IN_ISENTO CHAR(1)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_CLIENTE));
	
CREATE TABLE CAD_TRANSPORTADORA (
  CD_TRANSPORTADORA INTEGER   NOT NULL ,
  NM_RZ_SOCIAL VARCHAR(60)    ,
  NR_CNPJ_CPF VARCHAR(11)    ,
  NR_INSCRI_EST VARCHAR(15)    ,
  IN_ISENTO CHAR(1)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_TRANSPORTADORA));

CREATE TABLE CAD_PRODUTO_SERVICO (
  CD_PROSERV INTEGER   NOT NULL ,
  DS_PROSERV VARCHAR(60)    ,
  SG_UNIDMEDIDA CHAR(2)    ,
  VL_PROSERV NUMERIC    ,
  NR_NCM VARCHAR(15)    ,
  UN_COMERCIAL INTEGER    ,
  VL_UN_COMERCIAL NUMERIC(10,2)    ,
  UN_TRIBUTARIO INTEGER    ,
  QTDE_TRIBUTADO INTEGER    ,
  VL_UNIT_TRIBUTADO NUMERIC(10,2)    ,
  NR_CFOP VARCHAR(15)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_PROSERV));

CREATE TABLE MOV_EMITENTE_ENDERECO (
  CD_ENDERECO INTEGER   NOT NULL ,
  CD_EMITENTE INTEGER   NOT NULL   ,
PRIMARY KEY(CD_ENDERECO, CD_EMITENTE)    ,
  FOREIGN KEY(CD_ENDERECO)
    REFERENCES CAD_ENDERECO(CD_ENDERECO),
  FOREIGN KEY(CD_EMITENTE)
    REFERENCES CAD_EMITENTE(CD_EMITENTE));
	
CREATE TABLE MOV_CLIENTE_ENDERECO (
  CD_CLIENTE INTEGER   NOT NULL ,
  CD_ENDERECO INTEGER   NOT NULL   ,
PRIMARY KEY(CD_CLIENTE, CD_ENDERECO)    ,
  FOREIGN KEY(CD_ENDERECO)
    REFERENCES CAD_ENDERECO(CD_ENDERECO),
  FOREIGN KEY(CD_CLIENTE)
    REFERENCES CAD_CLIENTE(CD_CLIENTE));

CREATE TABLE MOV_TRANSPORTADORA_ENDERECO (
  CD_TRANSPORTADORA INTEGER   NOT NULL ,
  CD_ENDERECO INTEGER   NOT NULL   ,
PRIMARY KEY(CD_TRANSPORTADORA, CD_ENDERECO)    ,
  FOREIGN KEY(CD_ENDERECO)
    REFERENCES CAD_ENDERECO(CD_ENDERECO),
  FOREIGN KEY(CD_TRANSPORTADORA)
    REFERENCES CAD_TRANSPORTADORA(CD_TRANSPORTADORA));

CREATE TABLE MOV_NF (
  CD_NF INTEGER   NOT NULL ,
  CD_SERIE VARCHAR(2)   NOT NULL ,
  CD_MODALIDADE INTEGER   NOT NULL ,
  CD_TRANSPORTADORA INTEGER   NOT NULL ,
  CD_CLIENTE INTEGER   NOT NULL ,
  CD_EMITENTE INTEGER   NOT NULL ,
  CD_OPERACAO INTEGER   NOT NULL ,
  NR_PROTOCOLO_AUTORIZACAO_USO VARCHAR(60)    ,
  NR_CHAVE_ACESSO VARCHAR(60)    ,
  DT_EMISSAO DATE    ,
  DT_SAIDA DATE    ,
  HR_SAIDA VARCHAR(10)    ,
  VL_BASE_ICMS NUMERIC(10,2)    ,
  VL_BASE_ICMS_SUBIS NUMERIC(10,2)    ,
  VL_ICMS_SUBIS NUMERIC(10,2)    ,
  VL_TOTAL_ITENS NUMERIC(10,2)    ,
  VL_FRETE NUMERIC(10,2)    ,
  VL_SEGURO NUMERIC(10,2)    ,
  VL_DESCONTO NUMERIC(10,2)    ,
  VL_DESPESAS_ACESSORIOS NUMERIC(10,2)    ,
  VL_IPI NUMERIC(10,2)    ,
  VL_TOTAL_NF NUMERIC(10,2)    ,
  OBS_INFO_COMPL VARCHAR(600)      ,
PRIMARY KEY(CD_NF, CD_SERIE)          ,
  FOREIGN KEY(CD_OPERACAO)
    REFERENCES CAD_OPERACAO(CD_OPERACAO),
  FOREIGN KEY(CD_MODALIDADE)
    REFERENCES CAD_MODALIDADE_TRANSPORTE(CD_MODALIDADE),
  FOREIGN KEY(CD_CLIENTE)
    REFERENCES CAD_CLIENTE(CD_CLIENTE),
  FOREIGN KEY(CD_EMITENTE)
    REFERENCES CAD_EMITENTE(CD_EMITENTE),
  FOREIGN KEY(CD_TRANSPORTADORA)
    REFERENCES CAD_TRANSPORTADORA(CD_TRANSPORTADORA));

CREATE TABLE MOV_ITENS_NF (
  CD_PROSERV INTEGER   NOT NULL ,
  CD_SERIE VARCHAR(2)   NOT NULL ,
  CD_NF INTEGER   NOT NULL ,
  VL_UNITARIO NUMERIC(10,2)    ,
  VL_TOTAL NUMERIC(10,2)    ,
  VL_ICMS NUMERIC(10,2)    ,
  VL_IPI NUMERIC(10,2)    ,
  ALIQ_ICMS NUMERIC(10,2)    ,
  ALIQ_IPI NUMERIC(10,2)    ,
  NR_NCM NUMERIC(10,2)    ,
  CD_CST NUMERIC(10,2)    ,
  NR_CFOP VARCHAR(20)      ,
PRIMARY KEY(CD_PROSERV, CD_SERIE, CD_NF)    ,
  FOREIGN KEY(CD_NF, CD_SERIE)
    REFERENCES MOV_NF(CD_NF, CD_SERIE),
  FOREIGN KEY(CD_PROSERV)
    REFERENCES CAD_PRODUTO_SERVICO(CD_PROSERV));






