
CREATE TABLE CAD_PARAMETROS (
  CD_PARAMETROS INTEGER   NOT NULL ,
  DS_SV_PROXY VARCHAR2(100)    ,
  NR_PT_PROXY INTEGER    ,
  US_PROXY VARCHAR2(60)    ,
  PW_PROXY VARCHAR2(20)    ,
  DIR_LOTES_GERADOS VARCHAR2(100)    ,
  DOR_LOTES_AUTORIZADOS VARCHAR2(100)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_PARAMETROS));

CREATE TABLE CAD_CERTIFICADO_DIGITAL (
  CD_CERTIFICADO INTEGER   NOT NULL ,
  NM_CERTIFICADO VARCHAR2(60)    ,
  NR_CNPJ VARCHAR2(15)    ,
  DT_VALIDADE DATE    ,
  DS_EMISSOR VARCHAR2(100)    ,
  DS_LOCAL_ARQUIVO VARCHAR2(100)    ,
  TP_ARQUIVO VARCHAR2(10)    ,
  DS_LOCAL_BIBLIOTECAPKCS11 VARCHAR2(100)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_CERTIFICADO));

CREATE TABLE CAD_SERVICOS_WEB (
  CD_SERVICO INTEGER   NOT NULL ,
  NM_SERVICO VARCHAR2(60)    ,
  DS_VERSAO VARCHAR2(10)    ,
  DS_URL VARCHAR2(300)    ,
  IN_SVAN CHAR(1)    ,
  IN_SVRS CHAR(1)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_SERVICO));

CREATE TABLE CAD_USUARIO (
  CD_USUARIO INTEGER   NOT NULL ,
  NM_USUARIO VARCHAR2(60)    ,
  NM_LOGIN VARCHAR2(10)    ,
  PW_SENHA VARCHAR2(8)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_USUARIO));

INSERT INTO CAD_USUARIO(CD_USUARIO,NM_USUARIO,NM_LOGIN,PW_SENHA,DT_TRANSACAO)VALUES(1,'ADMINISTRADOR','ADMIN','ADMIN',SYSDATE);

CREATE TABLE CAD_PAIS (
  CD_PAIS INTEGER   NOT NULL ,
  NM_PAIS VARCHAR2(60)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_PAIS));

CREATE TABLE CAD_UF (
  CD_UF INTEGER   NOT NULL ,
  CD_PAIS INTEGER   NOT NULL ,
  SG_UF CHAR(2)    ,
  NM_UF VARCHAR2(60)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_UF)  ,
  FOREIGN KEY(CD_PAIS)
    REFERENCES CAD_PAIS(CD_PAIS));

CREATE TABLE CAD_CIDADE (
  CD_CIDADE INTEGER   NOT NULL ,
  CD_UF INTEGER   NOT NULL ,
  NM_CIDADE VARCHAR2(100)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_CIDADE)  ,
  FOREIGN KEY(CD_UF)
    REFERENCES CAD_UF(CD_UF));

CREATE TABLE CAD_ENDERECO (
  CD_ENDERECO INTEGER   NOT NULL ,
  CD_CIDADE INTEGER   NOT NULL ,
  DS_LOGRADOURO VARCHAR2(120)    ,
  DS_NUMERO VARCHAR2(40)    ,
  DS_COMPLEMENTO VARCHAR2(40)    ,
  DS_BAIRRO VARCHAR2(80)    ,
  NR_CEP VARCHAR2(10)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_ENDERECO)  ,
  FOREIGN KEY(CD_CIDADE)
    REFERENCES CAD_CIDADE(CD_CIDADE));

CREATE TABLE CAD_REGIME_TRIBUTARIO (
  CD_REGIME INTEGER   NOT NULL ,
  DS_REGIME VARCHAR2(60)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_REGIME));

CREATE TABLE CAD_OPERACAO (
  CD_OPERACAO INTEGER   NOT NULL ,
  NM_OPERACAO VARCHAR2(60)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_OPERACAO));

CREATE TABLE CAD_MODALIDADE_TRANSPORTE (
  CD_MODALIDADE INTEGER   NOT NULL ,
  DS_MODALIDADE VARCHAR2(60)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_MODALIDADE));

CREATE TABLE CAD_EMITENTE (
  CD_EMITENTE INTEGER   NOT NULL ,
  CD_REGIME INTEGER   NOT NULL ,
  NM_RZ_SOCIAL VARCHAR2(60)    ,
  NR_CNPJ_CPF VARCHAR2(11)    ,
  NR_INCRI_EST VARCHAR2(11)    ,
  NM_FANTASIA VARCHAR2(60)    ,
  DS_CENAE_FISCAL VARCHAR2(60)    ,
  NR_INCRI_MUNICIPAL VARCHAR2(15)    ,
  IMG_LOGO BLOB    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_EMITENTE)  ,
  FOREIGN KEY(CD_REGIME)
    REFERENCES CAD_REGIME_TRIBUTARIO(CD_REGIME));
	
CREATE TABLE CAD_CLIENTE (
  CD_CLIENTE INTEGER   NOT NULL ,
  NM_RZ_SOCIAL INTEGER    ,
  NR_CNPJ_CPF VARCHAR2(11)    ,
  NR_INSCRI_EST VARCHAR2(15)    ,
  DS_ANTT VARCHAR2(60)    ,
  DS_EMAIL VARCHAR2(60)    ,
  IN_ISENTO CHAR(1)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_CLIENTE));
	
CREATE TABLE CAD_TRANSPORTADORA (
  CD_TRANSPORTADORA INTEGER   NOT NULL ,
  NM_RZ_SOCIAL VARCHAR2(60)    ,
  NR_CNPJ_CPF VARCHAR2(11)    ,
  NR_INSCRI_EST VARCHAR2(15)    ,
  IN_ISENTO CHAR(1)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_TRANSPORTADORA));

CREATE TABLE CAD_PRODUTO_SERVICO (
  CD_PROSERV INTEGER   NOT NULL ,
  DS_PROSERV VARCHAR2(60)    ,
  SG_UNIDMEDIDA CHAR(2)    ,
  VL_PROSERV NUMBER    ,
  NR_NCM VARCHAR2(15)    ,
  UN_COMERCIAL INTEGER    ,
  VL_UN_COMERCIAL NUMBER(10,2)    ,
  UN_TRIBUTARIO INTEGER    ,
  QTDE_TRIBUTADO INTEGER    ,
  VL_UNIT_TRIBUTADO NUMBER(10,2)    ,
  NR_CFOP VARCHAR2(15)    ,
  DT_TRANSACAO DATE      ,
PRIMARY KEY(CD_PROSERV));

CREATE TABLE MOV_EMITENTE_ENDERECO (
  CD_ENDERECO INTEGER   NOT NULL ,
  CD_EMITENTE INTEGER   NOT NULL   ,
PRIMARY KEY(CD_ENDERECO, CD_EMITENTE)    ,
  FOREIGN KEY(CD_ENDERECO)
    REFERENCES CAD_ENDERECO(CD_ENDERECO),
  FOREIGN KEY(CD_EMITENTE)
    REFERENCES CAD_EMITENTE(CD_EMITENTE));
	
CREATE TABLE MOV_CLIENTE_ENDERECO (
  CD_CLIENTE INTEGER   NOT NULL ,
  CD_ENDERECO INTEGER   NOT NULL   ,
PRIMARY KEY(CD_CLIENTE, CD_ENDERECO)    ,
  FOREIGN KEY(CD_ENDERECO)
    REFERENCES CAD_ENDERECO(CD_ENDERECO),
  FOREIGN KEY(CD_CLIENTE)
    REFERENCES CAD_CLIENTE(CD_CLIENTE));

CREATE TABLE MOV_TRANSPORTADORA_ENDERECO (
  CD_TRANSPORTADORA INTEGER   NOT NULL ,
  CD_ENDERECO INTEGER   NOT NULL   ,
PRIMARY KEY(CD_TRANSPORTADORA, CD_ENDERECO)    ,
  FOREIGN KEY(CD_ENDERECO)
    REFERENCES CAD_ENDERECO(CD_ENDERECO),
  FOREIGN KEY(CD_TRANSPORTADORA)
    REFERENCES CAD_TRANSPORTADORA(CD_TRANSPORTADORA));

CREATE TABLE MOV_NF (
  CD_NF INTEGER   NOT NULL ,
  CD_SERIE VARCHAR2(2)   NOT NULL ,
  CD_MODALIDADE INTEGER   NOT NULL ,
  CD_TRANSPORTADORA INTEGER   NOT NULL ,
  CD_CLIENTE INTEGER   NOT NULL ,
  CD_EMITENTE INTEGER   NOT NULL ,
  CD_OPERACAO INTEGER   NOT NULL ,
  NR_PROTOCOLO_AUTORIZACAO_USO VARCHAR2(60)    ,
  NR_CHAVE_ACESSO VARCHAR2(60)    ,
  DT_EMISSAO DATE    ,
  DT_SAIDA DATE    ,
  HR_SAIDA VARCHAR2(10)    ,
  VL_BASE_ICMS NUMBER(10,2)    ,
  VL_BASE_ICMS_SUBIS NUMBER(10,2)    ,
  VL_ICMS_SUBIS NUMBER(10,2)    ,
  VL_TOTAL_ITENS NUMBER(10,2)    ,
  VL_FRETE NUMBER(10,2)    ,
  VL_SEGURO NUMBER(10,2)    ,
  VL_DESCONTO NUMBER(10,2)    ,
  VL_DESPESAS_ACESSORIOS NUMBER(10,2)    ,
  VL_IPI NUMBER(10,2)    ,
  VL_TOTAL_NF NUMBER(10,2)    ,
  OBS_INFO_COMPL VARCHAR2(600)      ,
PRIMARY KEY(CD_NF, CD_SERIE)          ,
  FOREIGN KEY(CD_OPERACAO)
    REFERENCES CAD_OPERACAO(CD_OPERACAO),
  FOREIGN KEY(CD_MODALIDADE)
    REFERENCES CAD_MODALIDADE_TRANSPORTE(CD_MODALIDADE),
  FOREIGN KEY(CD_CLIENTE)
    REFERENCES CAD_CLIENTE(CD_CLIENTE),
  FOREIGN KEY(CD_EMITENTE)
    REFERENCES CAD_EMITENTE(CD_EMITENTE),
  FOREIGN KEY(CD_TRANSPORTADORA)
    REFERENCES CAD_TRANSPORTADORA(CD_TRANSPORTADORA));

CREATE TABLE MOV_ITENS_NF (
  CD_PROSERV INTEGER   NOT NULL ,
  CD_SERIE VARCHAR2(2)   NOT NULL ,
  CD_NF INTEGER   NOT NULL ,
  VL_UNITARIO NUMBER(10,2)    ,
  VL_TOTAL NUMBER(10,2)    ,
  VL_ICMS NUMBER(10,2)    ,
  VL_IPI NUMBER(10,2)    ,
  ALIQ_ICMS NUMBER(10,2)    ,
  ALIQ_IPI NUMBER(10,2)    ,
  NR_NCM NUMBER(10,2)    ,
  CD_CST NUMBER(10,2)    ,
  NR_CFOP VARCHAR2(20)      ,
PRIMARY KEY(CD_PROSERV, CD_SERIE, CD_NF)    ,
  FOREIGN KEY(CD_NF, CD_SERIE)
    REFERENCES MOV_NF(CD_NF, CD_SERIE),
  FOREIGN KEY(CD_PROSERV)
    REFERENCES CAD_PRODUTO_SERVICO(CD_PROSERV));
    
    







