DROP TABLE MOV_ITENS_NF;
DROP TABLE MOV_NF;
DROP TABLE MOV_TRANSPORTADORA_ENDERECO;
DROP TABLE MOV_CLIENTE_ENDERECO;
DROP TABLE MOV_EMITENTE_ENDERECO;
DROP TABLE CAD_PRODUTO_SERVICO;
DROP TABLE CAD_TRANSPORTADORA;
DROP TABLE CAD_CLIENTE;
DROP TABLE CAD_EMITENTE;
DROP TABLE CAD_MODALIDADE_TRANSPORTE;
DROP TABLE CAD_OPERACAO;
DROP TABLE CAD_REGIME_TRIBUTARIO;
DROP TABLE CAD_ENDERECO;
DROP TABLE CAD_CIDADE;
DROP TABLE CAD_UF;
DROP TABLE CAD_PAIS;
DROP TABLE CAD_USUARIO;
DROP TABLE CAD_SERVICOS_WEB;
DROP TABLE CAD_CERTIFICADO_DIGITAL;
DROP TABLE CAD_PARAMETROS;


















