package br.com.genericnfe.view;

import br.com.genericnfe.dao.UsuarioDao;
import br.com.genericnfe.model.Banco;
import br.com.genericnfe.model.Usuario;
import br.com.genericnfe.tools.LookAndFeelWindows;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author jsoliveira
 */
public class Login extends javax.swing.JFrame {

    UsuarioDao uDao = new UsuarioDao();
    LookAndFeelWindows lafw = new LookAndFeelWindows();

    public Login() {
        initComponents();
        lafw.Windows(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBBanco = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jCBBase = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTfUsuario = new javax.swing.JTextField();
        jBtLimpar = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();
        jTfSenha = new javax.swing.JPasswordField();
        jBtEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Autenticação");
        setIconImages(null);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Usuário");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Senha");

        jCBBanco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oracle", "PostgreSQL" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Banco de Dados");

        jCBBase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Desenvolvimento", "Produção" }));
        jCBBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBBaseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Base");

        jTfUsuario.setText("admin");

        jBtLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtLimpar.setMnemonic('L');
        jBtLimpar.setText("Limpar");
        jBtLimpar.setPreferredSize(new java.awt.Dimension(80, 40));
        jBtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtLimparActionPerformed(evt);
            }
        });

        jBtSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtSair.setMnemonic('S');
        jBtSair.setText("Sair");
        jBtSair.setPreferredSize(new java.awt.Dimension(80, 40));
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSairActionPerformed(evt);
            }
        });

        jTfSenha.setText("admin");

        jBtEntrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtEntrar.setMnemonic('E');
        jBtEntrar.setText("Entrar");
        jBtEntrar.setPreferredSize(new java.awt.Dimension(80, 40));
        jBtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBBanco, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jCBBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTfSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTfUsuario, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-262)/2, (screenSize.height-294)/2, 262, 294);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtLimparActionPerformed

        jTfUsuario.setText("");
        jTfSenha.setText("");


    }//GEN-LAST:event_jBtLimparActionPerformed

    private void jBtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSairActionPerformed

        dispose();

    }//GEN-LAST:event_jBtSairActionPerformed

    private void jCBBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBBaseActionPerformed
    }//GEN-LAST:event_jCBBaseActionPerformed

    private void jBtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtEntrarActionPerformed
        Banco.setBanco(jCBBanco.getSelectedIndex());
        Banco.setBase(jCBBase.getSelectedIndex());

        if (!validaUser()) {

            JOptionPane.showMessageDialog(null, "Usuário ou senha incorreto(s)!");
            return;
        }

        telaPrincipal();
    }//GEN-LAST:event_jBtEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtEntrar;
    private javax.swing.JButton jBtLimpar;
    private javax.swing.JButton jBtSair;
    private javax.swing.JComboBox jCBBanco;
    private javax.swing.JComboBox jCBBase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jTfSenha;
    private javax.swing.JTextField jTfUsuario;
    // End of variables declaration//GEN-END:variables

    private Usuario getUsuario() {

        return new Usuario(0, null, jTfUsuario.getText(), new String(jTfSenha.getPassword()), null);
    }

    public boolean validaUser() {


        if (jTfUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o Usuário");
            jTfUsuario.grabFocus();
            return false;
        }

        if (new String(jTfSenha.getPassword()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe a Senha");
            jTfSenha.grabFocus();
            return false;
        }

       
        return uDao.validaLogin(getUsuario());
    }

    private void telaPrincipal() {

        TelaPrincipal tp = new TelaPrincipal();
        tp.jLabelUsuario.setText(jTfUsuario.getText());
        tp.jLabelBanco.setText(jCBBanco.getSelectedItem().toString());
        tp.jLabelBase.setText(jCBBase.getSelectedItem().toString());
        tp.jLabelDataLogin.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        tp.jLabelHoraLogin.setText(new SimpleDateFormat("hh:mm").format(new Date()));
        tp.setU(uDao.getUsuLogado());
        tp.setVisible(true);
        dispose();

    }
}
